### ISSUE TITLE
Mika56\SPFCheck\Exception\DNSLookupException

### ISSUE THREAD

**Issue by g00g1** [stilliard/stapps-debugger#5]
Hello,

Thanks for your service!

I would like to report issue with handling big DNS responses that causing your application to error. This information might help you to fix this problem:

```
Details
Type: Mika56\SPFCheck\Exception\DNSLookupException
Message: Response too big for UDP, retry with TCP
File: /srv/debugger/vendor/mika56/spfcheck/src/DNSRecordGetterDirect.php
Line: 177
Trace

#0 /srv/debugger/vendor/mika56/spfcheck/src/DNSRecordGetterDirect.php(62): Mika56\SPFCheck\DNSRecordGetterDirect->dns_get_record('netapp.com', 'TXT')
#1 /srv/debugger/src/helpers.php(11): Mika56\SPFCheck\DNSRecordGetterDirect->getSPFRecordForDomain('netapp.com')
#2 /srv/debugger/src/routes.php(22): spfChecker('netapp.com', '216.71.148.125')
#3 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 /srv/debugger/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /srv/debugger/vendor/slim/slim/Slim/Route.php(335): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /srv/debugger/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /srv/debugger/vendor/slim/slim/Slim/Route.php(313): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /srv/debugger/vendor/slim/slim/Slim/App.php(513): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /srv/debugger/vendor/slim/csrf/src/Guard.php(171): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 [internal function]: Slim\Csrf\Guard->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#11 /srv/debugger/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Slim\Csrf\Guard), Array)
#12 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#13 /srv/debugger/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#14 /srv/debugger/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /srv/debugger/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /srv/debugger/vendor/slim/slim/Slim/App.php(314): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /srv/debugger/public/index.php(30): Slim\App->run()
#18 {main}
```

**Comment by stilliard** [comment]
Hi @g00g1 
Thanks for spotting this, I've pushed a fix for this and it's live on the site now.
